modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/Christofmeg/AE2-QoL-Recipes/issues"
license="The MIT License (MIT)"
[[mods]]
modId="ae2qolrecipes"
version="${file.jarVersion}"
displayName="AE2 QoL Recipes"
displayURL="https://github.com/Christofmeg/AE2-QoL-Recipes"
logoFile="icon.png"
authors="Christofmeg, Lafen99"
description="QoL Recipes for Applied Energistics"
[[dependencies.ae2qolrecipes]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ae2qolrecipes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,)"
    ordering="NONE"
    side="BOTH"
[modproperties.ae2qolrecipes]
    catalogueItemIcon="ae2:fluix_glass_cable"
