# Project
java_version=21
version=1.3.0
group=com.christofmeg.ae2qolrecipes

# Mod options
mod_name=AE2 QoL Recipes
mod_authors=Christofmeg, Lafen99
mod_id=ae2qolrecipes
description=QoL Recipes for Applied Energistics
license=The MIT License (MIT)

# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Common | https://projects.neoforged.net/neoforged/neoform
minecraft_version=1.21.1
minecraft_version_range=1.21,1.22
neo_form_version=1.21.1-20240808.144430

# Parchment | https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_mc=1.21.1
parchment_version=2024.11.17

# NeoForge | https://projects.neoforged.net/neoforged/neoforge
neoforge_minecraft_version=1.21.1
neoforge_supported_versions=1.21.x
neoforge_version=21.1.116
neoforge_loader_version_range=[4,)
neoforge_version_range=[21,22)

# CurseForgeGradle | Minotaur options
cf_id=907026
modrinth_id=K7VSm2YY
release_type=release
neoforge_release_versions=1.21,1.21.1
