# Project
version=1.2.0
group=com.christofmeg.ae2qolrecipes

# Mod options
mod_name=AE2 QoL Recipes
mod_author=Christofmeg, Lafen99
mod_id=ae2qolrecipes

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Common
minecraft_version=1.17.1
supported_versions=1.17.1

jei_version=8.+

# Fabric | https://fabricmc.net/develop/
fabric_minecraft_version=1.17.1
fabric_supported_versions=1.17.1
fabric_version=0.46.1+1.17
fabric_loader_version=0.16.10

# Forge | https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=37.1.1

# Catalogue https://www.curseforge.com/minecraft/mc-mods/catalogue
catalogue_version=3529459

# Catalogue https://www.curseforge.com/minecraft/mc-mods/catalogue-fabric
#fabric_catalogue_version = 4590891

# CurseForgeGradle | Minotaur options
cf_id=907026
modrinth_id=K7VSm2YY
release_type=release
fabric_release_versions=1.17.1
forge_release_versions=1.17.1