# Project
java_version=17
version=1.2.0
group=com.christofmeg.ae2qolrecipes

# Mod options
mod_name=AE2 QoL Recipes
mod_authors=Christofmeg, Lafen99
mod_id=ae2qolrecipes
description=QoL Recipes for Applied Energistics
license=The MIT License (MIT)

# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Common
minecraft_version=1.20.2
minecraft_version_range=[1.20.2,1.20.5)

# Parchment | https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_mc=1.20.2
parchment_version=2023.12.10

# NeoForge | https://projects.neoforged.net/neoforged/neoforge
neoforge_minecraft_version=1.20.2
neoforge_supported_versions=1.20.2-1.20.4
neoforge_version=20.2.86
neoforge_loader_version_range=[1,)
neoforge_version_range=[20.2,)

# CurseForgeGradle | Minotaur options
cf_id=907026
modrinth_id=K7VSm2YY
release_type=release
neoforge_release_versions=1.20.2,1.20.4