import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'net.darkhax.curseforgegradle' version '1.+'
    id 'com.modrinth.minotaur' version '2.+'
}

base {
    archivesName = "${mod_id}-${project.name}-${neoforge_supported_versions}"
}

neoForge {
    version = neoforge_version

    parchment {
        minecraftVersion = parchment_mc
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            data()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    // JEI
    if (project.hasProperty('jei_version')) {
        if (project.hasProperty('enable_jei') && project.enable_jei.toBoolean()) {
            runtimeOnly("mezz.jei:jei-${jei_minecraft_version}-neoforge:${jei_version}")
        }
    }

    // CATALOGUE
    if (project.hasProperty('catalogue_version')) {
        implementation "curse.maven:catalogue-459701:${catalogue_version}"
    }
	
	implementation "maven.modrinth:ae2:FsBnZLCO" // https://modrinth.com/mod/ae2/versions
    implementation "maven.modrinth:guideme:EYCR81MC" // https://modrinth.com/mod/guideme/versions

}

tasks.register('publishCurseForge', TaskPublishCurseForge) {
    apiToken = file('../../API Tokens/ae2qolrecipes.md')
    def projectId = "${cf_id}".toString()
    def mainFile = upload(projectId, file("${project.buildDir}/libs/${archivesBaseName}-${version}.jar")) as Object
    mainFile.changelogType = 'markdown'
    mainFile.changelog = file('changelog.md')
    mainFile.addGameVersion('Client', 'Server')
    mainFile.releaseType = "${release_type}"
    "${neoforge_release_versions}".split(',').each {
        mainFile.addGameVersion("${it}")
    }
    mainFile.addRequirement("applied-energistics-2")
    mainFile.addOptional("catalogue")
}

modrinth {
    token = file('../../API Tokens/modrinth.md').text
    projectId = modrinth_id
    versionType = release_type
    changelog = file('changelog.md').text
    gameVersions = neoforge_release_versions.split(",") as List<String>
    loaders.add(project.name)
    detectLoaders = false
    versionName = "${archivesBaseName}-${version}"
    uploadFile = layout.buildDirectory.file("libs/${archivesBaseName}-${version}.jar").get().asFile

    dependencies {
        required.project "ae2"
    }
}